version: "2"

run:
  concurrency: 5
  go: '1.26'

linters:
  default: all
  disable:
    # Not suitable for this package
    - wrapcheck
    - gochecknoglobals
    - gomoddirectives
    - err113
    - depguard
  exclusions:
    rules:
      - path: '(.+)\.go$'
        text: ST1000
      - path: '(.+)\.go$'
        text: package-comments
      - path: '(.+)_test\.go'
        linters:
          - funlen
          - paralleltest
    paths:
      - vendor

formatters:
  disable:
    - gci
